// Copyright (C) 2025 Interactive Brokers LLC. All rights reserved. This code is subject to the terms
// and conditions of the IB API Non-Commercial License or the IB API Commercial License, as applicable.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v6.33.5
// source: AttachedOrders.proto

package v104401

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AttachedOrders struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SlOrderId   *int32  `protobuf:"varint,1,opt,name=slOrderId,proto3,oneof" json:"slOrderId,omitempty"`
	SlOrderType *string `protobuf:"bytes,2,opt,name=slOrderType,proto3,oneof" json:"slOrderType,omitempty"`
	PtOrderId   *int32  `protobuf:"varint,3,opt,name=ptOrderId,proto3,oneof" json:"ptOrderId,omitempty"`
	PtOrderType *string `protobuf:"bytes,4,opt,name=ptOrderType,proto3,oneof" json:"ptOrderType,omitempty"`
}

func (x *AttachedOrders) Reset() {
	*x = AttachedOrders{}
	if protoimpl.UnsafeEnabled {
		mi := &file_AttachedOrders_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AttachedOrders) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachedOrders) ProtoMessage() {}

func (x *AttachedOrders) ProtoReflect() protoreflect.Message {
	mi := &file_AttachedOrders_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachedOrders.ProtoReflect.Descriptor instead.
func (*AttachedOrders) Descriptor() ([]byte, []int) {
	return file_AttachedOrders_proto_rawDescGZIP(), []int{0}
}

func (x *AttachedOrders) GetSlOrderId() int32 {
	if x != nil && x.SlOrderId != nil {
		return *x.SlOrderId
	}
	return 0
}

func (x *AttachedOrders) GetSlOrderType() string {
	if x != nil && x.SlOrderType != nil {
		return *x.SlOrderType
	}
	return ""
}

func (x *AttachedOrders) GetPtOrderId() int32 {
	if x != nil && x.PtOrderId != nil {
		return *x.PtOrderId
	}
	return 0
}

func (x *AttachedOrders) GetPtOrderType() string {
	if x != nil && x.PtOrderType != nil {
		return *x.PtOrderType
	}
	return ""
}

var File_AttachedOrders_proto protoreflect.FileDescriptor

var file_AttachedOrders_proto_rawDesc = []byte{
	0x0a, 0x14, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x65, 0x64, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x22, 0xe0, 0x01, 0x0a, 0x0e, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x65, 0x64, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x73, 0x12, 0x21, 0x0a, 0x09, 0x73, 0x6c, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x09, 0x73, 0x6c, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x49, 0x64, 0x88, 0x01, 0x01, 0x12, 0x25, 0x0a, 0x0b, 0x73, 0x6c, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x0b, 0x73,
	0x6c, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x88, 0x01, 0x01, 0x12, 0x21, 0x0a,
	0x09, 0x70, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05,
	0x48, 0x02, 0x52, 0x09, 0x70, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x88, 0x01, 0x01,
	0x12, 0x25, 0x0a, 0x0b, 0x70, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x03, 0x52, 0x0b, 0x70, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x54, 0x79, 0x70, 0x65, 0x88, 0x01, 0x01, 0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x73, 0x6c, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x49, 0x64, 0x42, 0x0e, 0x0a, 0x0c, 0x5f, 0x73, 0x6c, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x54, 0x79, 0x70, 0x65, 0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x70, 0x74, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x49, 0x64, 0x42, 0x0e, 0x0a, 0x0c, 0x5f, 0x70, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x54,
	0x79, 0x70, 0x65, 0x42, 0x3e, 0x0a, 0x16, 0x63, 0x6f, 0x6d, 0x2e, 0x69, 0x62, 0x2e, 0x63, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x42, 0x13, 0x41,
	0x74, 0x74, 0x61, 0x63, 0x68, 0x65, 0x64, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0xaa, 0x02, 0x0e, 0x49, 0x42, 0x41, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_AttachedOrders_proto_rawDescOnce sync.Once
	file_AttachedOrders_proto_rawDescData = file_AttachedOrders_proto_rawDesc
)

func file_AttachedOrders_proto_rawDescGZIP() []byte {
	file_AttachedOrders_proto_rawDescOnce.Do(func() {
		file_AttachedOrders_proto_rawDescData = protoimpl.X.CompressGZIP(file_AttachedOrders_proto_rawDescData)
	})
	return file_AttachedOrders_proto_rawDescData
}

var file_AttachedOrders_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_AttachedOrders_proto_goTypes = []interface{}{
	(*AttachedOrders)(nil), // 0: protobuf.AttachedOrders
}
var file_AttachedOrders_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_AttachedOrders_proto_init() }
func file_AttachedOrders_proto_init() {
	if File_AttachedOrders_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_AttachedOrders_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AttachedOrders); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_AttachedOrders_proto_msgTypes[0].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_AttachedOrders_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_AttachedOrders_proto_goTypes,
		DependencyIndexes: file_AttachedOrders_proto_depIdxs,
		MessageInfos:      file_AttachedOrders_proto_msgTypes,
	}.Build()
	File_AttachedOrders_proto = out.File
	file_AttachedOrders_proto_rawDesc = nil
	file_AttachedOrders_proto_goTypes = nil
	file_AttachedOrders_proto_depIdxs = nil
}
