// Copyright (C) 2025 Interactive Brokers LLC. All rights reserved. This code is subject to the terms
// and conditions of the IB API Non-Commercial License or the IB API Commercial License, as applicable.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v6.33.5
// source: FamilyCodes.proto

package v104401

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FamilyCodes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FamilyCodes []*FamilyCode `protobuf:"bytes,1,rep,name=familyCodes,proto3" json:"familyCodes,omitempty"`
}

func (x *FamilyCodes) Reset() {
	*x = FamilyCodes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_FamilyCodes_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FamilyCodes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FamilyCodes) ProtoMessage() {}

func (x *FamilyCodes) ProtoReflect() protoreflect.Message {
	mi := &file_FamilyCodes_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FamilyCodes.ProtoReflect.Descriptor instead.
func (*FamilyCodes) Descriptor() ([]byte, []int) {
	return file_FamilyCodes_proto_rawDescGZIP(), []int{0}
}

func (x *FamilyCodes) GetFamilyCodes() []*FamilyCode {
	if x != nil {
		return x.FamilyCodes
	}
	return nil
}

var File_FamilyCodes_proto protoreflect.FileDescriptor

var file_FamilyCodes_proto_rawDesc = []byte{
	0x0a, 0x11, 0x46, 0x61, 0x6d, 0x69, 0x6c, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x1a, 0x10, 0x46,
	0x61, 0x6d, 0x69, 0x6c, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x45, 0x0a, 0x0b, 0x46, 0x61, 0x6d, 0x69, 0x6c, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x73, 0x12, 0x36,
	0x0a, 0x0b, 0x66, 0x61, 0x6d, 0x69, 0x6c, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x46,
	0x61, 0x6d, 0x69, 0x6c, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x0b, 0x66, 0x61, 0x6d, 0x69, 0x6c,
	0x79, 0x43, 0x6f, 0x64, 0x65, 0x73, 0x42, 0x3b, 0x0a, 0x16, 0x63, 0x6f, 0x6d, 0x2e, 0x69, 0x62,
	0x2e, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x42, 0x10, 0x46, 0x61, 0x6d, 0x69, 0x6c, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x73, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0xaa, 0x02, 0x0e, 0x49, 0x42, 0x41, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_FamilyCodes_proto_rawDescOnce sync.Once
	file_FamilyCodes_proto_rawDescData = file_FamilyCodes_proto_rawDesc
)

func file_FamilyCodes_proto_rawDescGZIP() []byte {
	file_FamilyCodes_proto_rawDescOnce.Do(func() {
		file_FamilyCodes_proto_rawDescData = protoimpl.X.CompressGZIP(file_FamilyCodes_proto_rawDescData)
	})
	return file_FamilyCodes_proto_rawDescData
}

var file_FamilyCodes_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_FamilyCodes_proto_goTypes = []interface{}{
	(*FamilyCodes)(nil), // 0: protobuf.FamilyCodes
	(*FamilyCode)(nil),  // 1: protobuf.FamilyCode
}
var file_FamilyCodes_proto_depIdxs = []int32{
	1, // 0: protobuf.FamilyCodes.familyCodes:type_name -> protobuf.FamilyCode
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_FamilyCodes_proto_init() }
func file_FamilyCodes_proto_init() {
	if File_FamilyCodes_proto != nil {
		return
	}
	file_FamilyCode_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_FamilyCodes_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FamilyCodes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_FamilyCodes_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_FamilyCodes_proto_goTypes,
		DependencyIndexes: file_FamilyCodes_proto_depIdxs,
		MessageInfos:      file_FamilyCodes_proto_msgTypes,
	}.Build()
	File_FamilyCodes_proto = out.File
	file_FamilyCodes_proto_rawDesc = nil
	file_FamilyCodes_proto_goTypes = nil
	file_FamilyCodes_proto_depIdxs = nil
}
