// Copyright (C) 2025 Interactive Brokers LLC. All rights reserved. This code is subject to the terms
// and conditions of the IB API Non-Commercial License or the IB API Commercial License, as applicable.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v6.33.5
// source: FamilyCode.proto

package v104401

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FamilyCode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountId  *string `protobuf:"bytes,1,opt,name=accountId,proto3,oneof" json:"accountId,omitempty"`
	FamilyCode *string `protobuf:"bytes,2,opt,name=familyCode,proto3,oneof" json:"familyCode,omitempty"`
}

func (x *FamilyCode) Reset() {
	*x = FamilyCode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_FamilyCode_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FamilyCode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FamilyCode) ProtoMessage() {}

func (x *FamilyCode) ProtoReflect() protoreflect.Message {
	mi := &file_FamilyCode_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FamilyCode.ProtoReflect.Descriptor instead.
func (*FamilyCode) Descriptor() ([]byte, []int) {
	return file_FamilyCode_proto_rawDescGZIP(), []int{0}
}

func (x *FamilyCode) GetAccountId() string {
	if x != nil && x.AccountId != nil {
		return *x.AccountId
	}
	return ""
}

func (x *FamilyCode) GetFamilyCode() string {
	if x != nil && x.FamilyCode != nil {
		return *x.FamilyCode
	}
	return ""
}

var File_FamilyCode_proto protoreflect.FileDescriptor

var file_FamilyCode_proto_rawDesc = []byte{
	0x0a, 0x10, 0x46, 0x61, 0x6d, 0x69, 0x6c, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x22, 0x71, 0x0a, 0x0a,
	0x46, 0x61, 0x6d, 0x69, 0x6c, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x21, 0x0a, 0x09, 0x61, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52,
	0x09, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x88, 0x01, 0x01, 0x12, 0x23, 0x0a,
	0x0a, 0x66, 0x61, 0x6d, 0x69, 0x6c, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x48, 0x01, 0x52, 0x0a, 0x66, 0x61, 0x6d, 0x69, 0x6c, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x88,
	0x01, 0x01, 0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64,
	0x42, 0x0d, 0x0a, 0x0b, 0x5f, 0x66, 0x61, 0x6d, 0x69, 0x6c, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x42,
	0x3a, 0x0a, 0x16, 0x63, 0x6f, 0x6d, 0x2e, 0x69, 0x62, 0x2e, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x42, 0x0f, 0x46, 0x61, 0x6d, 0x69, 0x6c,
	0x79, 0x43, 0x6f, 0x64, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0xaa, 0x02, 0x0e, 0x49, 0x42, 0x41,
	0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_FamilyCode_proto_rawDescOnce sync.Once
	file_FamilyCode_proto_rawDescData = file_FamilyCode_proto_rawDesc
)

func file_FamilyCode_proto_rawDescGZIP() []byte {
	file_FamilyCode_proto_rawDescOnce.Do(func() {
		file_FamilyCode_proto_rawDescData = protoimpl.X.CompressGZIP(file_FamilyCode_proto_rawDescData)
	})
	return file_FamilyCode_proto_rawDescData
}

var file_FamilyCode_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_FamilyCode_proto_goTypes = []interface{}{
	(*FamilyCode)(nil), // 0: protobuf.FamilyCode
}
var file_FamilyCode_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_FamilyCode_proto_init() }
func file_FamilyCode_proto_init() {
	if File_FamilyCode_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_FamilyCode_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FamilyCode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_FamilyCode_proto_msgTypes[0].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_FamilyCode_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_FamilyCode_proto_goTypes,
		DependencyIndexes: file_FamilyCode_proto_depIdxs,
		MessageInfos:      file_FamilyCode_proto_msgTypes,
	}.Build()
	File_FamilyCode_proto = out.File
	file_FamilyCode_proto_rawDesc = nil
	file_FamilyCode_proto_goTypes = nil
	file_FamilyCode_proto_depIdxs = nil
}
