// Copyright (C) 2025 Interactive Brokers LLC. All rights reserved. This code is subject to the terms
// and conditions of the IB API Non-Commercial License or the IB API Commercial License, as applicable.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v6.33.5
// source: HeadTimestamp.proto

package v104401

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HeadTimestamp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReqId         *int32  `protobuf:"varint,1,opt,name=reqId,proto3,oneof" json:"reqId,omitempty"`
	HeadTimestamp *string `protobuf:"bytes,2,opt,name=headTimestamp,proto3,oneof" json:"headTimestamp,omitempty"`
}

func (x *HeadTimestamp) Reset() {
	*x = HeadTimestamp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_HeadTimestamp_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeadTimestamp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeadTimestamp) ProtoMessage() {}

func (x *HeadTimestamp) ProtoReflect() protoreflect.Message {
	mi := &file_HeadTimestamp_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeadTimestamp.ProtoReflect.Descriptor instead.
func (*HeadTimestamp) Descriptor() ([]byte, []int) {
	return file_HeadTimestamp_proto_rawDescGZIP(), []int{0}
}

func (x *HeadTimestamp) GetReqId() int32 {
	if x != nil && x.ReqId != nil {
		return *x.ReqId
	}
	return 0
}

func (x *HeadTimestamp) GetHeadTimestamp() string {
	if x != nil && x.HeadTimestamp != nil {
		return *x.HeadTimestamp
	}
	return ""
}

var File_HeadTimestamp_proto protoreflect.FileDescriptor

var file_HeadTimestamp_proto_rawDesc = []byte{
	0x0a, 0x13, 0x48, 0x65, 0x61, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x22,
	0x71, 0x0a, 0x0d, 0x48, 0x65, 0x61, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x12, 0x19, 0x0a, 0x05, 0x72, 0x65, 0x71, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x48,
	0x00, 0x52, 0x05, 0x72, 0x65, 0x71, 0x49, 0x64, 0x88, 0x01, 0x01, 0x12, 0x29, 0x0a, 0x0d, 0x68,
	0x65, 0x61, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x48, 0x01, 0x52, 0x0d, 0x68, 0x65, 0x61, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x88, 0x01, 0x01, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x72, 0x65, 0x71, 0x49, 0x64,
	0x42, 0x10, 0x0a, 0x0e, 0x5f, 0x68, 0x65, 0x61, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x42, 0x3d, 0x0a, 0x16, 0x63, 0x6f, 0x6d, 0x2e, 0x69, 0x62, 0x2e, 0x63, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x42, 0x12, 0x48, 0x65,
	0x61, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0xaa, 0x02, 0x0e, 0x49, 0x42, 0x41, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_HeadTimestamp_proto_rawDescOnce sync.Once
	file_HeadTimestamp_proto_rawDescData = file_HeadTimestamp_proto_rawDesc
)

func file_HeadTimestamp_proto_rawDescGZIP() []byte {
	file_HeadTimestamp_proto_rawDescOnce.Do(func() {
		file_HeadTimestamp_proto_rawDescData = protoimpl.X.CompressGZIP(file_HeadTimestamp_proto_rawDescData)
	})
	return file_HeadTimestamp_proto_rawDescData
}

var file_HeadTimestamp_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_HeadTimestamp_proto_goTypes = []interface{}{
	(*HeadTimestamp)(nil), // 0: protobuf.HeadTimestamp
}
var file_HeadTimestamp_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_HeadTimestamp_proto_init() }
func file_HeadTimestamp_proto_init() {
	if File_HeadTimestamp_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_HeadTimestamp_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeadTimestamp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_HeadTimestamp_proto_msgTypes[0].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_HeadTimestamp_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_HeadTimestamp_proto_goTypes,
		DependencyIndexes: file_HeadTimestamp_proto_depIdxs,
		MessageInfos:      file_HeadTimestamp_proto_msgTypes,
	}.Build()
	File_HeadTimestamp_proto = out.File
	file_HeadTimestamp_proto_rawDesc = nil
	file_HeadTimestamp_proto_goTypes = nil
	file_HeadTimestamp_proto_depIdxs = nil
}
