// Copyright (C) 2025 Interactive Brokers LLC. All rights reserved. This code is subject to the terms
// and conditions of the IB API Non-Commercial License or the IB API Commercial License, as applicable.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v6.33.5
// source: IneligibilityReason.proto

package v104401

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IneligibilityReason struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          *string `protobuf:"bytes,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
	Description *string `protobuf:"bytes,2,opt,name=description,proto3,oneof" json:"description,omitempty"`
}

func (x *IneligibilityReason) Reset() {
	*x = IneligibilityReason{}
	if protoimpl.UnsafeEnabled {
		mi := &file_IneligibilityReason_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IneligibilityReason) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IneligibilityReason) ProtoMessage() {}

func (x *IneligibilityReason) ProtoReflect() protoreflect.Message {
	mi := &file_IneligibilityReason_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IneligibilityReason.ProtoReflect.Descriptor instead.
func (*IneligibilityReason) Descriptor() ([]byte, []int) {
	return file_IneligibilityReason_proto_rawDescGZIP(), []int{0}
}

func (x *IneligibilityReason) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *IneligibilityReason) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

var File_IneligibilityReason_proto protoreflect.FileDescriptor

var file_IneligibilityReason_proto_rawDesc = []byte{
	0x0a, 0x19, 0x49, 0x6e, 0x65, 0x6c, 0x69, 0x67, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x52,
	0x65, 0x61, 0x73, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x22, 0x68, 0x0a, 0x13, 0x49, 0x6e, 0x65, 0x6c, 0x69, 0x67, 0x69,
	0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12, 0x13, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x02, 0x69, 0x64, 0x88, 0x01,
	0x01, 0x12, 0x25, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x88, 0x01, 0x01, 0x42, 0x05, 0x0a, 0x03, 0x5f, 0x69, 0x64, 0x42,
	0x0e, 0x0a, 0x0c, 0x5f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x42,
	0x43, 0x0a, 0x16, 0x63, 0x6f, 0x6d, 0x2e, 0x69, 0x62, 0x2e, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x42, 0x18, 0x49, 0x6e, 0x65, 0x6c, 0x69,
	0x67, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0xaa, 0x02, 0x0e, 0x49, 0x42, 0x41, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_IneligibilityReason_proto_rawDescOnce sync.Once
	file_IneligibilityReason_proto_rawDescData = file_IneligibilityReason_proto_rawDesc
)

func file_IneligibilityReason_proto_rawDescGZIP() []byte {
	file_IneligibilityReason_proto_rawDescOnce.Do(func() {
		file_IneligibilityReason_proto_rawDescData = protoimpl.X.CompressGZIP(file_IneligibilityReason_proto_rawDescData)
	})
	return file_IneligibilityReason_proto_rawDescData
}

var file_IneligibilityReason_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_IneligibilityReason_proto_goTypes = []interface{}{
	(*IneligibilityReason)(nil), // 0: protobuf.IneligibilityReason
}
var file_IneligibilityReason_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_IneligibilityReason_proto_init() }
func file_IneligibilityReason_proto_init() {
	if File_IneligibilityReason_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_IneligibilityReason_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IneligibilityReason); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_IneligibilityReason_proto_msgTypes[0].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_IneligibilityReason_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_IneligibilityReason_proto_goTypes,
		DependencyIndexes: file_IneligibilityReason_proto_depIdxs,
		MessageInfos:      file_IneligibilityReason_proto_msgTypes,
	}.Build()
	File_IneligibilityReason_proto = out.File
	file_IneligibilityReason_proto_rawDesc = nil
	file_IneligibilityReason_proto_goTypes = nil
	file_IneligibilityReason_proto_depIdxs = nil
}
