// Copyright (C) 2025 Interactive Brokers LLC. All rights reserved. This code is subject to the terms
// and conditions of the IB API Non-Commercial License or the IB API Commercial License, as applicable.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v6.33.5
// source: MarketDepthExchanges.proto

package v104401

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MarketDepthExchanges struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DepthMarketDataDescriptions []*DepthMarketDataDescription `protobuf:"bytes,1,rep,name=depthMarketDataDescriptions,proto3" json:"depthMarketDataDescriptions,omitempty"`
}

func (x *MarketDepthExchanges) Reset() {
	*x = MarketDepthExchanges{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MarketDepthExchanges_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MarketDepthExchanges) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketDepthExchanges) ProtoMessage() {}

func (x *MarketDepthExchanges) ProtoReflect() protoreflect.Message {
	mi := &file_MarketDepthExchanges_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketDepthExchanges.ProtoReflect.Descriptor instead.
func (*MarketDepthExchanges) Descriptor() ([]byte, []int) {
	return file_MarketDepthExchanges_proto_rawDescGZIP(), []int{0}
}

func (x *MarketDepthExchanges) GetDepthMarketDataDescriptions() []*DepthMarketDataDescription {
	if x != nil {
		return x.DepthMarketDataDescriptions
	}
	return nil
}

var File_MarketDepthExchanges_proto protoreflect.FileDescriptor

var file_MarketDepthExchanges_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x4d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x44, 0x65, 0x70, 0x74, 0x68, 0x45, 0x78, 0x63,
	0x68, 0x61, 0x6e, 0x67, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x1a, 0x20, 0x44, 0x65, 0x70, 0x74, 0x68, 0x4d, 0x61, 0x72,
	0x6b, 0x65, 0x74, 0x44, 0x61, 0x74, 0x61, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x7e, 0x0a, 0x14, 0x4d, 0x61, 0x72, 0x6b,
	0x65, 0x74, 0x44, 0x65, 0x70, 0x74, 0x68, 0x45, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x73,
	0x12, 0x66, 0x0a, 0x1b, 0x64, 0x65, 0x70, 0x74, 0x68, 0x4d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x44,
	0x61, 0x74, 0x61, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x44, 0x65, 0x70, 0x74, 0x68, 0x4d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x44, 0x61, 0x74, 0x61,
	0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x1b, 0x64, 0x65, 0x70,
	0x74, 0x68, 0x4d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x44, 0x61, 0x74, 0x61, 0x44, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x42, 0x44, 0x0a, 0x16, 0x63, 0x6f, 0x6d, 0x2e,
	0x69, 0x62, 0x2e, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x42, 0x19, 0x4d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x44, 0x65, 0x70, 0x74, 0x68, 0x45,
	0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x73, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0xaa, 0x02, 0x0e,
	0x49, 0x42, 0x41, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_MarketDepthExchanges_proto_rawDescOnce sync.Once
	file_MarketDepthExchanges_proto_rawDescData = file_MarketDepthExchanges_proto_rawDesc
)

func file_MarketDepthExchanges_proto_rawDescGZIP() []byte {
	file_MarketDepthExchanges_proto_rawDescOnce.Do(func() {
		file_MarketDepthExchanges_proto_rawDescData = protoimpl.X.CompressGZIP(file_MarketDepthExchanges_proto_rawDescData)
	})
	return file_MarketDepthExchanges_proto_rawDescData
}

var file_MarketDepthExchanges_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_MarketDepthExchanges_proto_goTypes = []interface{}{
	(*MarketDepthExchanges)(nil),       // 0: protobuf.MarketDepthExchanges
	(*DepthMarketDataDescription)(nil), // 1: protobuf.DepthMarketDataDescription
}
var file_MarketDepthExchanges_proto_depIdxs = []int32{
	1, // 0: protobuf.MarketDepthExchanges.depthMarketDataDescriptions:type_name -> protobuf.DepthMarketDataDescription
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_MarketDepthExchanges_proto_init() }
func file_MarketDepthExchanges_proto_init() {
	if File_MarketDepthExchanges_proto != nil {
		return
	}
	file_DepthMarketDataDescription_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_MarketDepthExchanges_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MarketDepthExchanges); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_MarketDepthExchanges_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_MarketDepthExchanges_proto_goTypes,
		DependencyIndexes: file_MarketDepthExchanges_proto_depIdxs,
		MessageInfos:      file_MarketDepthExchanges_proto_msgTypes,
	}.Build()
	File_MarketDepthExchanges_proto = out.File
	file_MarketDepthExchanges_proto_rawDesc = nil
	file_MarketDepthExchanges_proto_goTypes = nil
	file_MarketDepthExchanges_proto_depIdxs = nil
}
