// Copyright (C) 2025 Interactive Brokers LLC. All rights reserved. This code is subject to the terms
// and conditions of the IB API Non-Commercial License or the IB API Commercial License, as applicable.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v6.33.5
// source: NewsBulletinsRequest.proto

package v104401

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NewsBulletinsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AllMessages *bool `protobuf:"varint,1,opt,name=allMessages,proto3,oneof" json:"allMessages,omitempty"`
}

func (x *NewsBulletinsRequest) Reset() {
	*x = NewsBulletinsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_NewsBulletinsRequest_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewsBulletinsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewsBulletinsRequest) ProtoMessage() {}

func (x *NewsBulletinsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_NewsBulletinsRequest_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewsBulletinsRequest.ProtoReflect.Descriptor instead.
func (*NewsBulletinsRequest) Descriptor() ([]byte, []int) {
	return file_NewsBulletinsRequest_proto_rawDescGZIP(), []int{0}
}

func (x *NewsBulletinsRequest) GetAllMessages() bool {
	if x != nil && x.AllMessages != nil {
		return *x.AllMessages
	}
	return false
}

var File_NewsBulletinsRequest_proto protoreflect.FileDescriptor

var file_NewsBulletinsRequest_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x4e, 0x65, 0x77, 0x73, 0x42, 0x75, 0x6c, 0x6c, 0x65, 0x74, 0x69, 0x6e, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x22, 0x4d, 0x0a, 0x14, 0x4e, 0x65, 0x77, 0x73, 0x42, 0x75,
	0x6c, 0x6c, 0x65, 0x74, 0x69, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x25,
	0x0a, 0x0b, 0x61, 0x6c, 0x6c, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x0b, 0x61, 0x6c, 0x6c, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x73, 0x88, 0x01, 0x01, 0x42, 0x0e, 0x0a, 0x0c, 0x5f, 0x61, 0x6c, 0x6c, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x73, 0x42, 0x44, 0x0a, 0x16, 0x63, 0x6f, 0x6d, 0x2e, 0x69, 0x62, 0x2e,
	0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x42,
	0x19, 0x4e, 0x65, 0x77, 0x73, 0x42, 0x75, 0x6c, 0x6c, 0x65, 0x74, 0x69, 0x6e, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0xaa, 0x02, 0x0e, 0x49, 0x42, 0x41,
	0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_NewsBulletinsRequest_proto_rawDescOnce sync.Once
	file_NewsBulletinsRequest_proto_rawDescData = file_NewsBulletinsRequest_proto_rawDesc
)

func file_NewsBulletinsRequest_proto_rawDescGZIP() []byte {
	file_NewsBulletinsRequest_proto_rawDescOnce.Do(func() {
		file_NewsBulletinsRequest_proto_rawDescData = protoimpl.X.CompressGZIP(file_NewsBulletinsRequest_proto_rawDescData)
	})
	return file_NewsBulletinsRequest_proto_rawDescData
}

var file_NewsBulletinsRequest_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_NewsBulletinsRequest_proto_goTypes = []interface{}{
	(*NewsBulletinsRequest)(nil), // 0: protobuf.NewsBulletinsRequest
}
var file_NewsBulletinsRequest_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_NewsBulletinsRequest_proto_init() }
func file_NewsBulletinsRequest_proto_init() {
	if File_NewsBulletinsRequest_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_NewsBulletinsRequest_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewsBulletinsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_NewsBulletinsRequest_proto_msgTypes[0].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_NewsBulletinsRequest_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_NewsBulletinsRequest_proto_goTypes,
		DependencyIndexes: file_NewsBulletinsRequest_proto_depIdxs,
		MessageInfos:      file_NewsBulletinsRequest_proto_msgTypes,
	}.Build()
	File_NewsBulletinsRequest_proto = out.File
	file_NewsBulletinsRequest_proto_rawDesc = nil
	file_NewsBulletinsRequest_proto_goTypes = nil
	file_NewsBulletinsRequest_proto_depIdxs = nil
}
