// Copyright (C) 2025 Interactive Brokers LLC. All rights reserved. This code is subject to the terms
// and conditions of the IB API Non-Commercial License or the IB API Commercial License, as applicable.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v6.33.5
// source: SmartComponents.proto

package v104401

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SmartComponents struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReqId           *int32            `protobuf:"varint,1,opt,name=reqId,proto3,oneof" json:"reqId,omitempty"`
	SmartComponents []*SmartComponent `protobuf:"bytes,2,rep,name=smartComponents,proto3" json:"smartComponents,omitempty"`
}

func (x *SmartComponents) Reset() {
	*x = SmartComponents{}
	if protoimpl.UnsafeEnabled {
		mi := &file_SmartComponents_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SmartComponents) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SmartComponents) ProtoMessage() {}

func (x *SmartComponents) ProtoReflect() protoreflect.Message {
	mi := &file_SmartComponents_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SmartComponents.ProtoReflect.Descriptor instead.
func (*SmartComponents) Descriptor() ([]byte, []int) {
	return file_SmartComponents_proto_rawDescGZIP(), []int{0}
}

func (x *SmartComponents) GetReqId() int32 {
	if x != nil && x.ReqId != nil {
		return *x.ReqId
	}
	return 0
}

func (x *SmartComponents) GetSmartComponents() []*SmartComponent {
	if x != nil {
		return x.SmartComponents
	}
	return nil
}

var File_SmartComponents_proto protoreflect.FileDescriptor

var file_SmartComponents_proto_rawDesc = []byte{
	0x0a, 0x15, 0x53, 0x6d, 0x61, 0x72, 0x74, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x1a, 0x14, 0x53, 0x6d, 0x61, 0x72, 0x74, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e,
	0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x7a, 0x0a, 0x0f, 0x53, 0x6d, 0x61, 0x72, 0x74,
	0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x19, 0x0a, 0x05, 0x72, 0x65,
	0x71, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x05, 0x72, 0x65, 0x71,
	0x49, 0x64, 0x88, 0x01, 0x01, 0x12, 0x42, 0x0a, 0x0f, 0x73, 0x6d, 0x61, 0x72, 0x74, 0x43, 0x6f,
	0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x6d, 0x61, 0x72, 0x74, 0x43,
	0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x52, 0x0f, 0x73, 0x6d, 0x61, 0x72, 0x74, 0x43,
	0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x73, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x72, 0x65,
	0x71, 0x49, 0x64, 0x42, 0x3f, 0x0a, 0x16, 0x63, 0x6f, 0x6d, 0x2e, 0x69, 0x62, 0x2e, 0x63, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x42, 0x14, 0x53,
	0x6d, 0x61, 0x72, 0x74, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x73, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0xaa, 0x02, 0x0e, 0x49, 0x42, 0x41, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_SmartComponents_proto_rawDescOnce sync.Once
	file_SmartComponents_proto_rawDescData = file_SmartComponents_proto_rawDesc
)

func file_SmartComponents_proto_rawDescGZIP() []byte {
	file_SmartComponents_proto_rawDescOnce.Do(func() {
		file_SmartComponents_proto_rawDescData = protoimpl.X.CompressGZIP(file_SmartComponents_proto_rawDescData)
	})
	return file_SmartComponents_proto_rawDescData
}

var file_SmartComponents_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_SmartComponents_proto_goTypes = []interface{}{
	(*SmartComponents)(nil), // 0: protobuf.SmartComponents
	(*SmartComponent)(nil),  // 1: protobuf.SmartComponent
}
var file_SmartComponents_proto_depIdxs = []int32{
	1, // 0: protobuf.SmartComponents.smartComponents:type_name -> protobuf.SmartComponent
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_SmartComponents_proto_init() }
func file_SmartComponents_proto_init() {
	if File_SmartComponents_proto != nil {
		return
	}
	file_SmartComponent_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_SmartComponents_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SmartComponents); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_SmartComponents_proto_msgTypes[0].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_SmartComponents_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_SmartComponents_proto_goTypes,
		DependencyIndexes: file_SmartComponents_proto_depIdxs,
		MessageInfos:      file_SmartComponents_proto_msgTypes,
	}.Build()
	File_SmartComponents_proto = out.File
	file_SmartComponents_proto_rawDesc = nil
	file_SmartComponents_proto_goTypes = nil
	file_SmartComponents_proto_depIdxs = nil
}
