// Copyright (C) 2025 Interactive Brokers LLC. All rights reserved. This code is subject to the terms
// and conditions of the IB API Non-Commercial License or the IB API Commercial License, as applicable.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v6.33.5
// source: TickAttribBidAsk.proto

package v104401

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TickAttribBidAsk struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BidPastLow  *bool `protobuf:"varint,1,opt,name=bidPastLow,proto3,oneof" json:"bidPastLow,omitempty"`
	AskPastHigh *bool `protobuf:"varint,2,opt,name=askPastHigh,proto3,oneof" json:"askPastHigh,omitempty"`
}

func (x *TickAttribBidAsk) Reset() {
	*x = TickAttribBidAsk{}
	if protoimpl.UnsafeEnabled {
		mi := &file_TickAttribBidAsk_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TickAttribBidAsk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TickAttribBidAsk) ProtoMessage() {}

func (x *TickAttribBidAsk) ProtoReflect() protoreflect.Message {
	mi := &file_TickAttribBidAsk_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TickAttribBidAsk.ProtoReflect.Descriptor instead.
func (*TickAttribBidAsk) Descriptor() ([]byte, []int) {
	return file_TickAttribBidAsk_proto_rawDescGZIP(), []int{0}
}

func (x *TickAttribBidAsk) GetBidPastLow() bool {
	if x != nil && x.BidPastLow != nil {
		return *x.BidPastLow
	}
	return false
}

func (x *TickAttribBidAsk) GetAskPastHigh() bool {
	if x != nil && x.AskPastHigh != nil {
		return *x.AskPastHigh
	}
	return false
}

var File_TickAttribBidAsk_proto protoreflect.FileDescriptor

var file_TickAttribBidAsk_proto_rawDesc = []byte{
	0x0a, 0x16, 0x54, 0x69, 0x63, 0x6b, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x42, 0x69, 0x64, 0x41,
	0x73, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x22, 0x7d, 0x0a, 0x10, 0x54, 0x69, 0x63, 0x6b, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62,
	0x42, 0x69, 0x64, 0x41, 0x73, 0x6b, 0x12, 0x23, 0x0a, 0x0a, 0x62, 0x69, 0x64, 0x50, 0x61, 0x73,
	0x74, 0x4c, 0x6f, 0x77, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x0a, 0x62, 0x69,
	0x64, 0x50, 0x61, 0x73, 0x74, 0x4c, 0x6f, 0x77, 0x88, 0x01, 0x01, 0x12, 0x25, 0x0a, 0x0b, 0x61,
	0x73, 0x6b, 0x50, 0x61, 0x73, 0x74, 0x48, 0x69, 0x67, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08,
	0x48, 0x01, 0x52, 0x0b, 0x61, 0x73, 0x6b, 0x50, 0x61, 0x73, 0x74, 0x48, 0x69, 0x67, 0x68, 0x88,
	0x01, 0x01, 0x42, 0x0d, 0x0a, 0x0b, 0x5f, 0x62, 0x69, 0x64, 0x50, 0x61, 0x73, 0x74, 0x4c, 0x6f,
	0x77, 0x42, 0x0e, 0x0a, 0x0c, 0x5f, 0x61, 0x73, 0x6b, 0x50, 0x61, 0x73, 0x74, 0x48, 0x69, 0x67,
	0x68, 0x42, 0x40, 0x0a, 0x16, 0x63, 0x6f, 0x6d, 0x2e, 0x69, 0x62, 0x2e, 0x63, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x42, 0x15, 0x54, 0x69, 0x63,
	0x6b, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x42, 0x69, 0x64, 0x41, 0x73, 0x6b, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0xaa, 0x02, 0x0e, 0x49, 0x42, 0x41, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_TickAttribBidAsk_proto_rawDescOnce sync.Once
	file_TickAttribBidAsk_proto_rawDescData = file_TickAttribBidAsk_proto_rawDesc
)

func file_TickAttribBidAsk_proto_rawDescGZIP() []byte {
	file_TickAttribBidAsk_proto_rawDescOnce.Do(func() {
		file_TickAttribBidAsk_proto_rawDescData = protoimpl.X.CompressGZIP(file_TickAttribBidAsk_proto_rawDescData)
	})
	return file_TickAttribBidAsk_proto_rawDescData
}

var file_TickAttribBidAsk_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_TickAttribBidAsk_proto_goTypes = []interface{}{
	(*TickAttribBidAsk)(nil), // 0: protobuf.TickAttribBidAsk
}
var file_TickAttribBidAsk_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_TickAttribBidAsk_proto_init() }
func file_TickAttribBidAsk_proto_init() {
	if File_TickAttribBidAsk_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_TickAttribBidAsk_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TickAttribBidAsk); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_TickAttribBidAsk_proto_msgTypes[0].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_TickAttribBidAsk_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_TickAttribBidAsk_proto_goTypes,
		DependencyIndexes: file_TickAttribBidAsk_proto_depIdxs,
		MessageInfos:      file_TickAttribBidAsk_proto_msgTypes,
	}.Build()
	File_TickAttribBidAsk_proto = out.File
	file_TickAttribBidAsk_proto_rawDesc = nil
	file_TickAttribBidAsk_proto_goTypes = nil
	file_TickAttribBidAsk_proto_depIdxs = nil
}
