// Copyright (C) 2025 Interactive Brokers LLC. All rights reserved. This code is subject to the terms
// and conditions of the IB API Non-Commercial License or the IB API Commercial License, as applicable.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v6.33.5
// source: UnsubscribeFromGroupEventsRequest.proto

package v104401

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UnsubscribeFromGroupEventsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReqId *int32 `protobuf:"varint,1,opt,name=reqId,proto3,oneof" json:"reqId,omitempty"`
}

func (x *UnsubscribeFromGroupEventsRequest) Reset() {
	*x = UnsubscribeFromGroupEventsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_UnsubscribeFromGroupEventsRequest_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnsubscribeFromGroupEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnsubscribeFromGroupEventsRequest) ProtoMessage() {}

func (x *UnsubscribeFromGroupEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_UnsubscribeFromGroupEventsRequest_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnsubscribeFromGroupEventsRequest.ProtoReflect.Descriptor instead.
func (*UnsubscribeFromGroupEventsRequest) Descriptor() ([]byte, []int) {
	return file_UnsubscribeFromGroupEventsRequest_proto_rawDescGZIP(), []int{0}
}

func (x *UnsubscribeFromGroupEventsRequest) GetReqId() int32 {
	if x != nil && x.ReqId != nil {
		return *x.ReqId
	}
	return 0
}

var File_UnsubscribeFromGroupEventsRequest_proto protoreflect.FileDescriptor

var file_UnsubscribeFromGroupEventsRequest_proto_rawDesc = []byte{
	0x0a, 0x27, 0x55, 0x6e, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x46, 0x72, 0x6f,
	0x6d, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x22, 0x48, 0x0a, 0x21, 0x55, 0x6e, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69,
	0x62, 0x65, 0x46, 0x72, 0x6f, 0x6d, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x05, 0x72, 0x65, 0x71, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x05, 0x72, 0x65, 0x71, 0x49, 0x64,
	0x88, 0x01, 0x01, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x72, 0x65, 0x71, 0x49, 0x64, 0x42, 0x51, 0x0a,
	0x16, 0x63, 0x6f, 0x6d, 0x2e, 0x69, 0x62, 0x2e, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x42, 0x26, 0x55, 0x6e, 0x73, 0x75, 0x62, 0x73, 0x63,
	0x72, 0x69, 0x62, 0x65, 0x46, 0x72, 0x6f, 0x6d, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0xaa,
	0x02, 0x0e, 0x49, 0x42, 0x41, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_UnsubscribeFromGroupEventsRequest_proto_rawDescOnce sync.Once
	file_UnsubscribeFromGroupEventsRequest_proto_rawDescData = file_UnsubscribeFromGroupEventsRequest_proto_rawDesc
)

func file_UnsubscribeFromGroupEventsRequest_proto_rawDescGZIP() []byte {
	file_UnsubscribeFromGroupEventsRequest_proto_rawDescOnce.Do(func() {
		file_UnsubscribeFromGroupEventsRequest_proto_rawDescData = protoimpl.X.CompressGZIP(file_UnsubscribeFromGroupEventsRequest_proto_rawDescData)
	})
	return file_UnsubscribeFromGroupEventsRequest_proto_rawDescData
}

var file_UnsubscribeFromGroupEventsRequest_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_UnsubscribeFromGroupEventsRequest_proto_goTypes = []interface{}{
	(*UnsubscribeFromGroupEventsRequest)(nil), // 0: protobuf.UnsubscribeFromGroupEventsRequest
}
var file_UnsubscribeFromGroupEventsRequest_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_UnsubscribeFromGroupEventsRequest_proto_init() }
func file_UnsubscribeFromGroupEventsRequest_proto_init() {
	if File_UnsubscribeFromGroupEventsRequest_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_UnsubscribeFromGroupEventsRequest_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnsubscribeFromGroupEventsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_UnsubscribeFromGroupEventsRequest_proto_msgTypes[0].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_UnsubscribeFromGroupEventsRequest_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_UnsubscribeFromGroupEventsRequest_proto_goTypes,
		DependencyIndexes: file_UnsubscribeFromGroupEventsRequest_proto_depIdxs,
		MessageInfos:      file_UnsubscribeFromGroupEventsRequest_proto_msgTypes,
	}.Build()
	File_UnsubscribeFromGroupEventsRequest_proto = out.File
	file_UnsubscribeFromGroupEventsRequest_proto_rawDesc = nil
	file_UnsubscribeFromGroupEventsRequest_proto_goTypes = nil
	file_UnsubscribeFromGroupEventsRequest_proto_depIdxs = nil
}
